[tool.poetry]
name = "grpc-custom-transformer"
version = "0.10.0rc0"
description = "gRPC custom transformer implementation. Not intended for use outside KServe Frameworks Images."
authors = ["Dan Sun <dsun20@bloomberg.net>"]
license = "https://github.com/kserve/kserve/blob/master/LICENSE"
packages = [
    { include = "*.py" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
kserve = {path = "../kserve", develop = true}
torchvision = {version = "0.14.0+cpu", source = "pytorch"}
pillow = "~9.0.1"


[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
