[tool.poetry]
name = "kserve"
version = "0.10.0rc0"
description = "KServe Python SDK"
authors = ["The KServe Authors"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/kserve/kserve/tree/master/python/kserve"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "kserve" },
]

[tool.poetry.dependencies]
python = "^3.7"
uvicorn = "^0.16.0"
fastapi = "^0.85.0"
cloudevents = "^1.6.2"
six = "^1.16.0"
urllib3 = "^1.26.8"
kubernetes = "^18.20.0"
python-dateutil = "^2.8.0"
google-cloud-storage = "^1.20.0"
table-logger = "^0.3.6"
numpy = "^1.21.1"
azure-storage-blob = "12.9.0"
azure-storage-file-share = "12.7.0"
azure-identity = "^1.8.0"
boto3 = "1.21.0"
psutil = "^5.9.0"
ray = {version = "2.0.0", extras = ["serve"]}
grpcio = "^1.34.0"
protobuf = "~3.19.0"
prometheus-client = "^0.13.1"
orjson = "^3.8.0"
httpx = "^0.23.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-xdist = "^3.0.2"
pytest-asyncio = "^0.20.2"
mypy = "^0.991"
portforward = "^0.3.0"
avro = "^1.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
