name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Poetry install path
    - run: |
        export $POETRY_HOME=~/.local/share/pypoetry
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.1
    - name: Install poetry version plugin
      run: |
        ${POETRY_HOME}/venv/bin/activate
        pip install -e python/plugin/poetry-version-plugin
        poetry self show plugins   
    - name: Build and publish
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd python/kserve
        poetry build
        poetry publish
