name: Twice a week scan
# Temporarily adding on push for testing
on:
  # on pull request will be removed before merge
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

jobs:
  base-image-scan:
    name: scan images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [{ name: kserve-controller, file: Dockerfile},
                { name: agent, file: agent.Dockerfile},
                { name: storage-initializer, file: python/storage-initializer.Dockerfile}]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kserve/${{ matrix.image.name }}
          args: --severity-threshold=low
                --file={{ matrix.image.file }}
                --sarif-file-output=./application/${{ matrix.image.name }}/docker.snyk.sarif
          sarif: false

      - name: Upload sarif file to Github Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: application/${{ matrix.image.name }}/docker.snyk.sarif
