name: Twice a week scan
# Temporarily adding on push for testing
on:
  push:
    branches: [ snyk-scan ]
  pull_request:
    branches: []

jobs:
  base-image-scan:
    name: scan images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [kserve-controller, agent, storage-initializer]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kserve/${{ matrix.image }}
          args: --severity-threshold=low
  
  predictor-image-scan:
    name: scan predictor images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [sklearnserver, xgbserver, pmmlserver, paddleserver]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kserve/${{ matrix.image }}
          args: --severity-threshold=low
  
  explainer-image-scan:
    name: scan explainer images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [aix-explainer, alibi-explainer, art-explainer]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Security scan on docker image
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kserve/${{ matrix.image }}
          args: --severity-threshold=low