name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is being marked stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is being marked stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because there has been no activity for 7 days after adding stale label'
          days-before-stale: 90
          days-before-close: 7
          days-before-pr-stale: 90
          days-before-pr-close: 10